full_name = "Kristine Vilnite"
description = "Compassionate innovator, founder, advisor, sustainable development advocate. Kristine adds value by unlocking power of diversity, simplicity and genuinity towards complex challenges assuring that a positive net impact on the planet is a norm. Building a sustainable foundation for the future and just being a loving, kind, explorer is what Kristine calls a good day on this beautiful planet."
function = "Partnerships"
linkedin= "https://www.linkedin.com/in/kristinevilnite/"
rank = 0
project_ids = ["1"]
contribution_ids = ["3"]
nationality = "Latvian"
